spring:
  datasource:
    url: jdbc:postgresql://localhost:5123/postgres?currentSchema=volvic
    username: postgres
    password: 1574
    driver-class-name: org.postgresql.Driver


  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

mybatis:
  type-aliases-package: org.park.firstbatch
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml